server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost/flow?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowMultiQueries=true&serverTimezone=UTC&nullCatalogMeansCurrent=true
    username: root
    password: root
tomcat:
  uri-encoding: UTF-8
logging:
  level.root: info
  level.com.bonade: debug
  path: logs/
  file: flowable-test.log


---
logging:
  level.root: warn
  path: logs/
  file: flowable-test.log